### ISSUE TITLE
Suggestion: Rate of increase config

### ISSUE THREAD

**Issue by Tyrius1** [Sarinsa/Apocalypse-Rebooted#7]
A config to tweak the rate at which your difficulty increases would be nice to have! Something like a 0-100 where at 0 your difficulty doesn't increase at all and at 100 your difficulty increases 100 times as fast?

**Comment by Sarinsa** [comment]
The general idea is that difficulty should to some degree reflect how long a player has played (in days). The only exceptions really being sleeping (punishing skipping the night or thunderstorms by adding additional difficulty), and optional dimension penalty where difficulty increases faster to encourage the player to do swift business in the dimension they are in to avoid having their difficulty increase significantly.

**Comment by Sarinsa** [comment]
However this doesn't mean that monster stats, equipment and potion effects are strictly bound. The idea is to have all these things be configurable in order to let players and pack creators balance the game as they see fit. Potion effects and equipment is currently not implemented, but monster stat bonuses are indeed! Everything from attack damage, speed bonus, knockback resistance bonus, health bonus etc. is fully configurable
